# Generated by Django 4.0.4 on 2022-05-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfol', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
